### PR TITLE
Move to sideway

### PR DESCRIPTION
**Pull request by jameschensmith**
Moves project from Hapi to Sideway.

### CODE REVIEW

**Comment by vicmars5** [comment]
Hi! I would like to know what the current status of this MR? Is there a way I can help to fix the issues in the pipeline?

**Comment by jameschensmith** [comment]
@vicmars5, when I initially made this PR, the build hung for quite a long time (if you look at the build details, you can see it ran for over an hour). It also appears to have failed on the latest version of Node.js. I haven't heard from @hueniverse, but this change is all I planned on making to switch the project from Hapi to Sideway.

So, in short, this PR is pending on a response from the maintainer(s).

**Comment by hueniverse** [comment]
Thanks but this is the wrong npm namespace.

**Comment by jameschensmith** [comment]
> Thanks but this is the wrong npm namespace.

Oof. Wasn't aware. Thanks for checking in, @hueniverse! 🙂

**Pull request closed without merging**
